### ISSUE TITLE
環境の決定

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/site#1]
次のような構成を考えています。

Domain/DNS: Amazon Route53
Serve: Netlify( free )
Git: GitHub( https://github.com/Polymer-Japan に作成 )

どうでしょうか？

**Comment by sizuhiko** [comment]
もしサイトをPolymerで作るのなら今回のDev FestサイトみたいにFirebaseアプリにしてしまうのもありかな、とは思いますが、提案の通りでも良いとは思います。
Dev Festのサイト構築を習得しておくと、来年のサイト担当になれるかもしれないというやましい気持ちが多少ないとは言いませんw

**Comment by aggre** [comment]
@sizuhiko Netlify はデプロイの CI を組まなくて良いところが気に入ってます...が、チームが有料なのに気づきました😨
Firebase か Netlify かはすぐ切り替えれらるので先にほかの issue を進めます。

**Comment by aggre** [comment]
Firebase Hosting を利用に決定しました。
