### ISSUE TITLE
ドメインの取得

### ISSUE THREAD

**Issue by aggre** [Polymer-Japan/site#2]
polymer-project.jp
polymer-japan.com

...などは空いています。
`polymer.*` はほぼ空きなしです。( https://instantdomainsearch.com/#search=polymer )

決定すれば私が Amazon Route53 で取得しようと思います。
なにがいいでしょう？

**Comment by aggre** [comment]
追加: polymer-jp.org

**Comment by sizuhiko** [comment]
polymer-project.jp

**Comment by aggre** [comment]
変更の場合もリダイレクトできますので、いったん polymer-jp.org に決定しました。
